services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nozama
    networks:
      - nozama-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: maven:3.9.9-eclipse-temurin-21
    container_name: spring_app_dev
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2   # Cache do Maven para acelerar os builds
    networks:
      - nozama-network
    ports:
      - "8080:8080"
      - "8000:8000"
    command: >
      sh -c "mvn spring-boot:run 
      -Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000'"

networks:
  nozama-network:
    driver: bridge

volumes:
  postgres_data:
